"""user table add column

Revision ID: d0a0c6888a1b
Revises: fd30a378dcf7
Create Date: 2024-10-19 16:16:49.761955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a0c6888a1b'
down_revision: Union[str, None] = 'fd30a378dcf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rate_limit', ['id'])
    op.create_unique_constraint(None, 'tier', ['id'])
    op.create_unique_constraint(None, 'token_blacklist', ['id'])
    op.add_column('user', sa.Column('test_column', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_column')
    op.drop_constraint(None, 'token_blacklist', type_='unique')
    op.drop_constraint(None, 'tier', type_='unique')
    op.drop_constraint(None, 'rate_limit', type_='unique')
    # ### end Alembic commands ###
