"""alter user table

Revision ID: cab39cd3495e
Revises: 34c082a96d57
Create Date: 2024-10-20 21:56:12.305977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab39cd3495e'
down_revision: Union[str, None] = '34c082a96d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_column', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_column')
    # ### end Alembic commands ###
